### ISSUE TITLE
Будет ли расширение для safari?

### ISSUE THREAD

**Issue by egor-sh** [adictgroup/don-t-call-back-me#1]
Собственно сабж. Планируется ли порт на сафари? Расширение хорошее, респект :)

**Comment by adictgroup** [comment]
Приветствую @egor-sh! 
Думаем что пора уже закрыть этот тикет. 
Скоро планируется обновление плагина, но вот разработка плагина для Safari теперь точно не планируется. Вы можете сделать его сами, основываясь на нашем коде или попросить друзей сделать такой плагин.
Мы же, можем порекомендовать плагин https://github.com/bcye/Hello-Goodbye
У него есть реализация для Safari и iOS.  Он имеет схожий функционал и обладает такой же полезностью ;)

Спасибо за отзыв
